# Generated by Django 4.1.5 on 2023-02-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='posts',
            field=models.ManyToManyField(to='blogs.blog'),
        ),
    ]
