# Generated by Django 4.1.5 on 2023-02-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='posts',
        ),
    ]
