# Generated by Django 4.1.5 on 2023-02-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(2, 'Deleted'), (0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
