# Generated by Django 4.1.5 on 2023-01-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='edited_tima',
            new_name='edited_time',
        ),
    ]
