# Generated by Django 4.1.5 on 2023-01-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_edited_tima_post_edited_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
