# Generated by Django 4.1.5 on 2023-02-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_blogs_blog_id_2a3e37_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Published'), (1, 'Deleted')], default=0),
        ),
    ]
