# Generated by Django 4.1.5 on 2023-01-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_events_even_name_d5901c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, upload_to='events/images/'),
        ),
    ]
