# Generated by Django 4.1.5 on 2023-02-07 06:53

from django.db import migrations, models
from django.utils.text import slugify

def generate_slug_for_existing_records(apps, schema_editor):
    print('Generating slug for existing events...')

    Event = apps.get_model("events", "Event")
    qs = Event.objects.all()

    for event in qs:
        event.slug = slugify(event.name)
        event.save() 


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=256, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, upload_to='events/images/', verbose_name='Poster'),
        ),
        migrations.RunPython(generate_slug_for_existing_records, migrations.RunPython.noop),
    ]
