"""message_author_id

Revision ID: 1cc6f6b3fbd9
Revises: 89e532fd23ca
Create Date: 2023-03-20 21:24:19.394841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc6f6b3fbd9'
down_revision = '89e532fd23ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'author_id')
    # ### end Alembic commands ###
