"""message_author_id

Revision ID: 7c9a4a87934a
Revises: 1831f7fda240
Create Date: 2023-03-20 21:23:46.297518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9a4a87934a'
down_revision = '1831f7fda240'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'author_id')
    # ### end Alembic commands ###
