# Generated by Django 4.1.7 on 2023-03-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='sign',
            field=models.IntegerField(choices=[(1, 'Aries'), (2, 'Taurus'), (3, 'Twins'), (4, 'Cancer'), (5, 'Leo'), (6, 'Virgo'), (7, 'Libra'), (8, 'Scorpius'), (9, 'Sagittarius'), (10, 'Capricornus'), (11, 'Aquarius'), (12, 'Fish')]),
        ),
        migrations.DeleteModel(
            name='Signs',
        ),
    ]
