# Generated by Django 4.1.7 on 2023-03-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope_api', '0002_alter_horoscope_sign_delete_signs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='sign',
            field=models.CharField(choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Twins', 'Twins'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpius', 'Scorpius'), ('Sagittarius', 'Sagittarius'), ('Capricornus', 'Capricornus'), ('Aquearius', 'Aquarius'), ('fish', 'Fish')], max_length=64),
        ),
    ]
