# Generated by Django 4.1.7 on 2023-04-06 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope_api', '0004_alter_horoscope_date_alter_horoscope_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='date',
            field=models.DateField(default=datetime.date(2023, 4, 6)),
        ),
    ]
