DECIMAL_SEPARATOR = ' '
THOUSAND_SEPARATOR = ','
NUMBER_GROUPING = 2


DATE_FORMAT = '%Y-%m-%d'
DATE_INPUT_FORMATS = ('%d/%m/%Y', '%Y-%m-%d')
DATETIME_INPUT_FORMATS = ('%d/%m/%Y %H:%M:%S', '%Y-%m-%d %H:%M:%S')