# Generated by Django 4.2 on 2023-04-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='categories__name_e3ad98_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='categories__slug_9b1a28_idx'),
        ),
    ]
