# Generated by Django 4.1.5 on 2023-02-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_blog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id'], name='posts_post_id_06b5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['blog'], name='posts_post_blog_id_dbe9f3_idx'),
        ),
    ]
