# Generated by Django 4.1.5 on 2023-02-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_satus_delete_alter_post_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='satus_delete',
            new_name='status_delete',
        ),
    ]
