# Generated by Django 4.1.5 on 2023-02-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['id'], name='blogs_blog_id_2a3e37_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['author'], name='blogs_blog_author__166d94_idx'),
        ),
    ]
