# Generated by Django 4.2 on 2023-04-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customerreview_admin_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Deleted')], default=0),
        ),
    ]
