# Generated by Django 4.2 on 2023-04-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customerreview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='customer_review',
            field=models.TextField(verbose_name='Отзыв'),
        ),
    ]
