# Generated by Django 4.2 on 2023-05-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customerreview_customer_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreview',
            options={'ordering': ['-creation_date']},
        ),
    ]
