# Generated by Django 4.1.5 on 2023-02-10 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_blogs_blog_id_2a3e37_idx_and_more'),
        ('posts', '0003_post_posts_post_id_06b5f3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='blogs.blog'),
        ),
    ]
